---
title: "Forecasting Demand v.07"
author: "Arif P. Sulistiono / @arifpras"
date: "2023-01-26"
output: html_document
---

```{r prerequisites, include=FALSE}
# From {usethis} to avoid loading a massive .RData file
usethis::use_blank_slate(scope = c("user", "project"))

# Removes all items in Environment!
rm(list = ls())
ls()

# Load packages
# pacman::p_load(tidyverse, seasonal, fpp2, readxl, devtools, feasts, qpdf, wesanderson, lubridate, zoo, tsibble)

pacman::p_load(tidyverse, seasonal, fpp2, readxl, devtools, feasts, qpdf, wesanderson, lubridate, zoo, tsibble, scales, tidyquant, gridExtra, tibbletime, forecast, itsmr, here, tseries)

knitr::opts_chunk$set(comment=NA,tidy=FALSE)

# My ggplot's themes
devtools::source_url("https://raw.githubusercontent.com/arifpras/themesAPS/main/themesAPS?raw=TRUE")

options(tz = "Asia/Jakarta")

# https://www.kaggle.com/code/brwalk/an-introduction-to-time-series-forecasting-in-r
# https://www.mitchelloharawild.com/blog/feasts/
# https://medium.com/analytics-vidhya/a-complete-introduction-to-time-series-analysis-with-r-exogenous-models-4f009b770104
```

```{r working-dir, include=FALSE}
setwd("~/Dropbox/01_Kemenkeu/2022_11/forecastingDemand")
```

```{r load}
db01 <- read_csv("~/Dropbox/01_Kemenkeu/2022_11/forecastingDemand/20230126_database.csv", show_col_types = FALSE)

db01$month <-
  as.Date(db01$month, "%Y-%m-%d")

summary(db01)
```

```{r}
db02 <- ts(db01[,2:7], start = c(2012, 1), end = c(2022, 6), frequency = 12)
summary(db02)
```

```{r}
# subset the data 
db03 <- db02[,c(1,5)]

# plot the data
autoplot(db03, facets=TRUE) +
  xlab("") + ylab("") +
  ggtitle("Incoming bid and VIX index")
  
# plot the ACF
ggAcf(db03)

# plot the ACF
ggPacf(db03)
```

```{r decomposition_bid_sun}
# fit a Classical decomposition model  for incoming bid
db04_bidsun = db03[, "incoming_bid_avg_sun"] %>% ts(., frequency = 12) # freq = 12 months
db04_bidsun_stl = stl(db04_bidsun, s.window = "periodic")
autoplot(db04_bidsun_stl)
```

```{r}
# fit a Classical decomposition model for VIX index
db04_vixi = db03[, "vix_index"] %>% ts(., frequency = 12) # freq = 12 months
db04_vixi_stl = stl(db04_vixi, s.window = "periodic")
autoplot(db04_vixi_stl)
```

```{r include=FALSE}
incomingbidsun_arimax = auto.arima(
  db03[, "incoming_bid_avg_sun"],
  # specify main trend
  xreg = db03[, "vix_index"],
  # specify exogenous variables here
  trace = TRUE,
  seasonal = FALSE,
  stepwise = FALSE,
  approximation = FALSE
)

# Best model: Regression with ARIMA(2,1,2)            errors
```

```{r}
summary(incomingbidsun_arimax)
```

```{r}
autoplot(incomingbidsun_arimax)
```

```{r}
checkresiduals(incomingbidsun_arimax)
```

```{r}
test(resid(incomingbidsun_arimax))
```

```{r sarimax, include=FALSE}
incomingbidsun_sarimax = auto.arima(
  db03[, "incoming_bid_avg_sun"],
  # specify main trend
  xreg = db03[, "vix_index"],
  # specify exogenous variables here
  trace = TRUE,
  seasonal = TRUE, # allow a SARIMAX model
  stepwise = FALSE,
  approximation = FALSE
)

# Best model: Regression with ARIMA(1,1,3)(1,0,0)[12] errors
```

```{r}
summary(incomingbidsun_sarimax)
```

```{r}
autoplot(incomingbidsun_sarimax)
```

```{r}
checkresiduals(incomingbidsun_sarimax)
```

```{r}
test(resid(incomingbidsun_sarimax))
```

```{r}
# correclty specify the series
db05 <-
  ts(
    db03,
    frequency = 12,
    start = c(2012, 1),
    end = c(2022, 6)
  )

# split the data into train and test sets
db05_train <- window(db05, end = c(2021, 12))
db05_test <- window(db05, start = c(2022, 1))

# retrain model only on train data
incomingbidsun_arimax2 = auto.arima(
  db05_train[, "incoming_bid_avg_sun"],
  # specify main trend
  xreg = db05_train[, "vix_index"],
  # specify exogenous variables here
  trace = FALSE,
  # do not show iffted models
  seasonal = FALSE,
  # do not allow a SARIMAX model
  stepwise = FALSE,
  approximation = FALSE
)

## produce forecasts
forecast_arimax <-
  forecast::forecast(incomingbidsun_arimax2, xreg = rep(db05_test[, "incoming_bid_avg_sun"], 6))

## plot the forecasts
autoplot(forecast_arimax) + autolayer(db05[, "incoming_bid_avg_sun"]) + theme(legend.position = "bottom") + xlim(2012, 2022.5)
```

```{r}
# correclty specify the series
db05 <-
  ts(
    db03,
    frequency = 12,
    start = c(2012, 1),
    end = c(2022, 6)
  )

# split the data into train and test sets
db05_train <- window(db05, end = c(2021, 12))
db05_test <- window(db05, start = c(2022, 1))

# retrain model only on train data
incomingbidsun_sarimax2 = auto.arima(
  db05_train[, "incoming_bid_avg_sun"],
  # specify main trend
  xreg = db05_train[, "vix_index"],
  # specify exogenous variables here
  trace = FALSE,
  # do not show iffted models
  seasonal = TRUE,
  # do not allow a SARIMAX model
  stepwise = FALSE,
  approximation = FALSE
)

## produce forecasts
forecast_sarimax <-
  forecast::forecast(incomingbidsun_sarimax2, xreg = rep(db05_test[, "incoming_bid_avg_sun"], 6))

## plot the forecasts
autoplot(forecast_sarimax) + autolayer(db05[, "incoming_bid_avg_sun"]) + theme(legend.position = "bottom") + xlim(2012, 2022.5)
```

```{r}
# Removes all items in Environment!
rm(list = ls())
ls()
```

